### ISSUE TITLE
Using tests as filters is deprecated. Instead of using `result|failed` use `result is failed`. 

### ISSUE THREAD

**Issue by dac514** [softasap/sa-publishing-kindlegen#1]
When running in newer versions of Ansible I get:

> TASK [kindlegen : KindleGen | download package] ********************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using
`result|failed` use `result is failed`. This feature will be removed in version
 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
changed: [default]

> TASK [kindlegen : KindleGen | Create installation directory] *******************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using
`result|failed` use `result is failed`. This feature will be removed in version
 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
changed: [default]

> TASK [kindlegen : KindleGen | Unarchieve installation] *************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using
`result|failed` use `result is failed`. This feature will be removed in version
 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
changed: [default]

> TASK [kindlegen : KindleGen | Link executable] *********************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using
`result|failed` use `result is failed`. This feature will be removed in version
 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

**Comment by Voronenko** [comment]
@tgjohnst  Thank you for your input. I have added also pass with fixes reported by ansible-lint.
